import type { Service } from "./types";

/**
 * Master Service Index — 114 services, locked v1.0.
 * Each entry uses the four-line GEO citation format: what it is, when you need
 * it, what you receive, where it operates. Multi-class services list the
 * primary class first; cross-classes carried in `crossClass`.
 */
export const SERVICES: Service[] = [
  {
    number: 1,
    slug: "site-selection-venue-sourcing",
    name: "Site Selection & Venue Sourcing",
    primaryClass: "4000",
    apsLevels: ["L1", "L2"],
    primaryPhase: "01",
    secondaryPhases: ["02", "04"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "End-to-end venue research and recommendation across raw land, ticketed venues, hotels, stadiums, marinas, theme parks, vessels, and private estates.",
    whenYouNeed: "Phase 01 Discovery, before creative direction is locked.",
    whatYouReceive:
      "A shortlist of three to seven venues with comparative matrices on capacity, infrastructure, permit posture, cost, and brand fit.",
    whereItOperates:
      "APS L1, L2. Markets: Miami, New York City, Chicago, Los Angeles, plus national and international sourcing.",
  },
  {
    number: 2,
    slug: "site-survey-technical-recce",
    name: "Site Survey & Technical Recce",
    primaryClass: "4000",
    apsLevels: ["L2", "L3"],
    primaryPhase: "01",
    secondaryPhases: ["02", "03"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "On-site walkthrough capturing measurements, power infrastructure, rigging points, sightlines, ingress / egress, and ADA constraints.",
    whenYouNeed: "Phase 01 Discovery into Phase 02 Concept.",
    whatYouReceive: "CAD-ready site survey, photo and video documentation, technical assessment report.",
    whereItOperates: "APS L2, L3.",
  },
  {
    number: 3,
    slug: "wayfinding-signage-strategy",
    name: "Wayfinding & Signage Strategy",
    primaryClass: "1000",
    crossClass: ["4000"],
    apsLevels: ["L3", "L4"],
    primaryPhase: "02",
    secondaryPhases: ["03", "05"],
    tiers: ["04", "05"],
    whatItIs:
      "Guest navigation system covering external arrival, internal zoning, ADA wayfinding, and brand-integrated signage architecture.",
    whenYouNeed: "Phase 02 Concept, with print production in Phase 05 Build.",
    whatYouReceive: "Wayfinding master plan, sign schedule, fabrication-ready artwork.",
    whereItOperates: "APS L3, L4.",
  },
  {
    number: 4,
    slug: "perimeter-mot-planning",
    name: "Perimeter & Maintenance-of-Traffic Planning",
    primaryClass: "6000",
    apsLevels: ["L2", "L3"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "Exterior operations plan covering vehicle routing, lane closures, drop-off design, and pedestrian / vehicular separation.",
    whenYouNeed: "Phase 03 Develop, executed in Phase 05 Build.",
    whatYouReceive: "MOT plan stamped or unstamped per jurisdiction, signed barricade plan, exterior crew map.",
    whereItOperates: "APS L2, L3.",
  },
  {
    number: 5,
    slug: "site-power-utility-planning",
    name: "Site Power & Utility Infrastructure Planning",
    primaryClass: "5000",
    apsLevels: ["L3"],
    primaryPhase: "03",
    secondaryPhases: ["05"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "Load calculation, distribution architecture, generator placement, and tie-in coordination across electrical, water, fuel, HVAC.",
    whenYouNeed: "Phase 03 Develop.",
    whatYouReceive: "Power plan, distro schedule, generator order, fuel logistics.",
    whereItOperates: "APS L3.",
  },
  {
    number: 6,
    slug: "crowd-flow-egress-engineering",
    name: "Crowd Flow & Egress Engineering",
    primaryClass: "6000",
    apsLevels: ["L2", "L3"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "Modeled guest movement covering entry surge, internal capacity zoning, queue design, and emergency egress.",
    whenYouNeed: "Phase 03 Develop, validated in Phase 05 Build.",
    whatYouReceive: "Flow simulation, capacity matrix, egress certification package.",
    whereItOperates: "APS L2, L3.",
  },
  {
    number: 7,
    slug: "site-sustainability-environmental-assessment",
    name: "Site Sustainability & Environmental Assessment",
    primaryClass: "0000",
    apsLevels: ["L1", "L2"],
    primaryPhase: "01",
    secondaryPhases: ["03", "08"],
    tiers: ["04", "05"],
    whatItIs:
      "Pre-event impact study covering waste streams, energy sourcing, water usage, ground impact, and habitat considerations.",
    whenYouNeed: "Phase 01 Discovery.",
    whatYouReceive: "Sustainability brief, mitigation plan, post-event measurement framework.",
    whereItOperates: "APS L1 Project, L2 Event.",
  },
  {
    number: 8,
    slug: "audio-system-design-deployment",
    name: "Audio System Design & Deployment",
    primaryClass: "5000",
    apsLevels: ["L4", "L5", "L6"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "PA, monitors, FOH, distributed audio, and zoned audio systems engineered to venue acoustics and program needs.",
    whenYouNeed: "Phase 02 Concept; built in Phase 05; operated in Phase 06.",
    whatYouReceive: "System design, equipment list, EASE / Mapp predictions, A1 / A2 staffing, signal flow.",
    whereItOperates: "APS L4, L5, L6.",
  },
  {
    number: 9,
    slug: "lighting-design-rigging-engineering",
    name: "Lighting Design & Rigging Engineering",
    primaryClass: "5000",
    apsLevels: ["L4", "L5"],
    primaryPhase: "02",
    secondaryPhases: ["03", "05", "06"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "Lighting plot, fixture schedule, rigging plan, dimmer / data architecture, and programming for entertainment, hospitality, and architectural needs.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Light plot, rigging plan, cue stack, programmer staffing.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 10,
    slug: "video-led-projection-integration",
    name: "Video, LED & Projection Integration",
    primaryClass: "5000",
    apsLevels: ["L4", "L5"],
    primaryPhase: "02",
    secondaryPhases: ["03", "05", "06"],
    tiers: ["02", "04", "05", "06"],
    whatItIs: "IMAG, content playback, LED wall design, projection mapping, and creative content delivery systems.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Video system design, content delivery plan, LED panel schedule, V1 staffing.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 11,
    slug: "power-distribution-generator-engineering",
    name: "Power Distribution & Generator Engineering",
    primaryClass: "5000",
    apsLevels: ["L3", "L5"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "Distro design from utility tie-in or generator through panels to fixtures, including cable schedule and load balancing.",
    whenYouNeed: "Phase 03 Develop.",
    whatYouReceive: "Distro plan, cable pull schedule, generator order, fuel plan, electrician staffing.",
    whereItOperates: "APS L3, L5.",
  },
  {
    number: 12,
    slug: "network-it-comms-infrastructure",
    name: "Network, IT & Comms Infrastructure",
    primaryClass: "9000",
    apsLevels: ["L3", "L5"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06"],
    tiers: ["02", "03", "04", "05"],
    whatItIs: "Wired / wireless networks, IPTV, intercom, two-way radios, and dedicated production VLANs.",
    whenYouNeed: "Phase 03 Develop.",
    whatYouReceive: "Network architecture, IP plan, comms plan, IT technician staffing.",
    whereItOperates: "APS L3, L5.",
  },
  {
    number: 13,
    slug: "broadcast-livestream-multicam-production",
    name: "Broadcast, Livestream & Multicam Production",
    primaryClass: "5000",
    crossClass: ["9000"],
    apsLevels: ["L4"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["02", "03", "06"],
    whatItIs: "Multi-camera capture, livestream encoding, social cutdowns, post-event highlight production.",
    whenYouNeed: "Phase 02 Concept; executed Phase 06 Show.",
    whatYouReceive: "Broadcast plan, camera schedule, livestream architecture, post-production deliverables.",
    whereItOperates: "APS L4.",
  },
  {
    number: 14,
    slug: "show-control-smpte-cue-programming",
    name: "Show Control, SMPTE & Cue Programming",
    primaryClass: "5000",
    apsLevels: ["L4", "L5"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "Timecoded show integration tying audio, lighting, video, pyro, and automation into a synchronized cue stack.",
    whenYouNeed: "Phase 03 Develop through Phase 06 Show.",
    whatYouReceive: "Show control architecture, cue stack, programmer staffing, redundancy plan.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 15,
    slug: "rf-wireless-coordination",
    name: "RF & Wireless Coordination",
    primaryClass: "9000",
    apsLevels: ["L3", "L5"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05", "06"],
    whatItIs: "Spectrum management for wireless mics, IEMs, comms, and IoT devices in dense RF environments.",
    whenYouNeed: "Phase 03 Develop.",
    whatYouReceive: "RF coordination plan, frequency assignments, FCC filings where required.",
    whereItOperates: "APS L3, L5.",
  },
  {
    number: 16,
    slug: "vip-lounge-buildout-service-design",
    name: "VIP Lounge Buildout & Service Design",
    primaryClass: "8000",
    apsLevels: ["L3", "L4"],
    primaryPhase: "02",
    secondaryPhases: ["03", "05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "End-to-end design and operation of premium guest spaces with curated environment, F&B, service standards, and capacity flow.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Lounge design, service standards binder, staffing plan, guest journey map.",
    whereItOperates: "APS L3, L4.",
  },
  {
    number: 17,
    slug: "guest-registration-rfid-credentialing",
    name: "Guest Registration, RFID & Credentialing",
    primaryClass: "9000",
    crossClass: ["7000"],
    apsLevels: ["L3", "L4"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06"],
    tiers: ["02", "04", "05"],
    whatItIs:
      "Pre-event registration platform, on-site check-in, RFID / NFC credentials, access control, and post-event data capture.",
    whenYouNeed: "Phase 03 Develop through Phase 06 Show.",
    whatYouReceive: "Registration platform, credential design, scanner deployment, data export.",
    whereItOperates: "APS L3, L4.",
  },
  {
    number: 18,
    slug: "concierge-host-program-staffing",
    name: "Concierge & Host Program Staffing",
    primaryClass: "7000",
    apsLevels: ["L4"],
    primaryPhase: "05",
    secondaryPhases: ["06"],
    tiers: ["04", "05"],
    whatItIs: "Trained concierge and host teams managing VIP arrival, in-event service, and post-event follow-up.",
    whenYouNeed: "Phase 05 Build through Phase 06 Show.",
    whatYouReceive: "Trained staff, service playbooks, daily reports.",
    whereItOperates: "APS L4.",
  },
  {
    number: 19,
    slug: "premium-suite-box-operations",
    name: "Premium Suite & Box Operations",
    primaryClass: "8000",
    apsLevels: ["L3", "L4"],
    primaryPhase: "05",
    secondaryPhases: ["06"],
    tiers: ["04", "05"],
    whatItIs: "Suite-level F&B, service, and amenity programs for stadium / arena / marina box environments.",
    whenYouNeed: "Phase 05 Build through Phase 06 Show.",
    whatYouReceive: "Suite operations binder, in-suite F&B program, host staffing.",
    whereItOperates: "APS L3, L4.",
  },
  {
    number: 20,
    slug: "talent-green-room-backstage-hospitality",
    name: "Talent Green Room & Backstage Hospitality",
    primaryClass: "8000",
    crossClass: ["2000"],
    apsLevels: ["L3", "L4"],
    primaryPhase: "05",
    secondaryPhases: ["06"],
    tiers: ["04", "05", "06"],
    whatItIs: "Rider fulfillment, talent comfort spaces, dressing rooms, and artist day-of-show flow.",
    whenYouNeed: "Phase 05 Build through Phase 06 Show.",
    whatYouReceive: "Rider checklist, room buildout, talent runner staffing.",
    whereItOperates: "APS L3, L4.",
  },
  {
    number: 21,
    slug: "brand-side-hospitality-programming",
    name: "Brand-Side Hospitality Programming",
    primaryClass: "7000",
    apsLevels: ["L1", "L4"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["01", "04", "05"],
    whatItIs:
      "Custom brand activations layered over hospitality footprint — talks, demos, exclusive moments, premium experiences.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Programming calendar, host scripting, content capture.",
    whereItOperates: "APS L1, L4.",
  },
  {
    number: 22,
    slug: "fb-menu-development-sourcing",
    name: "F&B Menu Development & Sourcing",
    primaryClass: "8000",
    apsLevels: ["L4"],
    primaryPhase: "02",
    secondaryPhases: ["03", "06"],
    tiers: ["04", "05"],
    whatItIs: "Brand-aligned menu architecture, ingredient sourcing, dietary accommodation, and supplier negotiation.",
    whenYouNeed: "Phase 02 Concept.",
    whatYouReceive: "Menu architecture, sourcing matrix, cost breakdown.",
    whereItOperates: "APS L4.",
  },
  {
    number: 23,
    slug: "bar-program-design-cocktail-menu",
    name: "Bar Program Design & Cocktail Menu",
    primaryClass: "8000",
    apsLevels: ["L4", "L5"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs: "Custom cocktail menus, bar layout, glassware, ice program, and bar back operations.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Cocktail menu, bar layout, prep schedule, bartender staffing.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 24,
    slug: "catering-operations-management",
    name: "Catering Operations Management",
    primaryClass: "8000",
    apsLevels: ["L4"],
    primaryPhase: "04",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "Catering vendor selection, kitchen logistics, service flow, and on-site catering management for crew and guest meals.",
    whenYouNeed: "Phase 04 Advance through Phase 06 Show.",
    whatYouReceive: "Catering schedule, dietary tracker, on-site catering manager.",
    whereItOperates: "APS L4.",
  },
  {
    number: 25,
    slug: "mobile-bar-food-truck-integration",
    name: "Mobile Bar & Food Truck Integration",
    primaryClass: "8000",
    apsLevels: ["L4", "L5"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs: "Sourcing, branding, integration, and coordination of mobile F&B units within an activation footprint.",
    whenYouNeed: "Phase 03 Develop through Phase 06 Show.",
    whatYouReceive: "Mobile unit roster, branding wraps, integration plan.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 26,
    slug: "sampling-activation-operations",
    name: "Sampling Activation Operations",
    primaryClass: "7000",
    crossClass: ["8000"],
    apsLevels: ["L4"],
    primaryPhase: "02",
    secondaryPhases: ["03", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "Branded product sampling at scale — staffing, distribution mechanics, compliance, and consumer data capture.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Sampling plan, compliance checklist, staffing, data capture.",
    whereItOperates: "APS L4.",
  },
  {
    number: 27,
    slug: "liquor-licensing-tips-compliance",
    name: "Liquor Licensing & TIPS Compliance",
    primaryClass: "0000",
    apsLevels: ["L1", "L2"],
    primaryPhase: "03",
    secondaryPhases: ["06"],
    tiers: ["04", "05"],
    whatItIs: "Special-event liquor permits, TIPS-certified service, and on-premise consumption compliance.",
    whenYouNeed: "Phase 03 Develop through Phase 06 Show.",
    whatYouReceive: "Liquor permit, TIPS-certified staff roster, compliance plan.",
    whereItOperates: "APS L1, L2.",
  },
  {
    number: 28,
    slug: "pop-up-retail-buildout",
    name: "Pop-Up Retail Buildout",
    primaryClass: "7000",
    apsLevels: ["L3", "L4"],
    primaryPhase: "02",
    secondaryPhases: ["03", "05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "Branded retail environment design, fixturing, lighting, and operational playbook for short-duration activations.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Retail design, fixture schedule, operations binder.",
    whereItOperates: "APS L3, L4.",
  },
  {
    number: 29,
    slug: "pos-payment-inventory-systems",
    name: "POS, Payment & Inventory Systems",
    primaryClass: "9000",
    apsLevels: ["L4", "L5"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06"],
    tiers: ["02", "04", "05"],
    whatItIs:
      "Point-of-sale platform deployment, payment processing, real-time inventory tracking, and post-event reconciliation.",
    whenYouNeed: "Phase 03 Develop through Phase 06 Show.",
    whatYouReceive: "POS deployment, payment integration, inventory dashboard.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 30,
    slug: "custom-merchandise-design-fulfillment",
    name: "Custom Merchandise Design & Fulfillment",
    primaryClass: "7000",
    crossClass: ["1000"],
    apsLevels: ["L4", "L5"],
    primaryPhase: "02",
    secondaryPhases: ["03", "06"],
    tiers: ["01", "04", "05"],
    whatItIs: "Custom apparel, premium goods, and exclusive drops with sourcing, production, and fulfillment.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Merch line sheet, production schedule, fulfillment plan.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 31,
    slug: "ecommerce-extension-post-event-sales",
    name: "E-Commerce Extension & Post-Event Sales",
    primaryClass: "7000",
    crossClass: ["9000"],
    apsLevels: ["L1"],
    primaryPhase: "02",
    secondaryPhases: ["08"],
    tiers: ["01", "02", "04"],
    whatItIs: "Online storefront, drop campaigns, and post-event commerce strategy extending the activation lifecycle.",
    whenYouNeed: "Phase 02 Concept through Phase 08 Wrap.",
    whatYouReceive: "Storefront, drop calendar, post-event sales reporting.",
    whereItOperates: "APS L1.",
  },
  {
    number: 32,
    slug: "production-office-buildout",
    name: "Production Office Buildout",
    primaryClass: "6000",
    apsLevels: ["L2", "L3"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs: "On-site production HQ with desk plan, network, printing, comms, supplies, and security.",
    whenYouNeed: "Phase 03 Develop through Phase 06 Show.",
    whatYouReceive: "Office layout, IT / comms plan, supply order, daily operations.",
    whereItOperates: "APS L2, L3.",
  },
  {
    number: 33,
    slug: "crew-workspace-break-rooms",
    name: "Crew Workspace & Break Rooms",
    primaryClass: "6000",
    apsLevels: ["L3", "L4"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs: "Crew rest spaces, charging stations, food / water stations, and personnel hygiene infrastructure.",
    whenYouNeed: "Phase 03 Develop through Phase 06 Show.",
    whatYouReceive: "Crew space layout, supply order, daily restock.",
    whereItOperates: "APS L3, L4.",
  },
  {
    number: 34,
    slug: "production-document-file-management",
    name: "Production Document & File Management",
    primaryClass: "0000",
    apsLevels: ["L1", "L2"],
    primaryPhase: "01",
    secondaryPhases: "all",
    tiers: ["04", "05"],
    whatItIs: "Centralized document control covering contracts, permits, COIs, plots, runs of show, and archival.",
    whenYouNeed: "Phase 01 Discovery through Phase 08 Wrap.",
    whatYouReceive: "Document repository, version control, RBAC access matrix.",
    whereItOperates: "APS L1, L2.",
  },
  {
    number: 35,
    slug: "production-office-supplies-consumables",
    name: "Production Office Supplies & Consumables",
    primaryClass: "6000",
    apsLevels: ["L4", "L6"],
    primaryPhase: "04",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs: "Curated supply order spanning office, comms, sanitation, signage, PPE, and operational consumables.",
    whenYouNeed: "Phase 04 Advance through Phase 06 Show.",
    whatYouReceive: "Supply order, advance ship, on-site delivery, par-level restock.",
    whereItOperates: "APS L4, L6.",
  },
  {
    number: 36,
    slug: "production-internet-printing-comms",
    name: "Production Internet, Printing & Comms",
    primaryClass: "9000",
    crossClass: ["6000"],
    apsLevels: ["L3"],
    primaryPhase: "04",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs: "Dedicated internet, printer fleet, two-way radios, and intra-team messaging deployment.",
    whenYouNeed: "Phase 04 Advance through Phase 06 Show.",
    whatYouReceive: "Internet circuits, printer deployment, radio / comms plan.",
    whereItOperates: "APS L3.",
  },
  {
    number: 37,
    slug: "talent-travel-logistics",
    name: "Talent Travel Logistics",
    primaryClass: "6000",
    crossClass: ["2000"],
    apsLevels: ["L1", "L2"],
    primaryPhase: "04",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05", "06"],
    whatItIs: "Flight booking, ground transport, accommodations, and rider compliance for talent.",
    whenYouNeed: "Phase 04 Advance through Phase 06 Show.",
    whatYouReceive: "Talent itinerary, ground plan, accommodation schedule.",
    whereItOperates: "APS L1, L2.",
  },
  {
    number: 38,
    slug: "crew-accommodations-management",
    name: "Crew Accommodations Management",
    primaryClass: "6000",
    crossClass: ["8000"],
    apsLevels: ["L1", "L2"],
    primaryPhase: "04",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs: "Block-booked hotels, room assignments, billing, and on-site crew accommodation support.",
    whenYouNeed: "Phase 04 Advance through Phase 06 Show.",
    whatYouReceive: "Room block, assignment matrix, billing reconciliation.",
    whereItOperates: "APS L1, L2.",
  },
  {
    number: 39,
    slug: "ground-transportation-coordination",
    name: "Ground Transportation Coordination",
    primaryClass: "6000",
    apsLevels: ["L2"],
    primaryPhase: "04",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs: "Town cars, sprinter vans, motor coaches, and shuttle systems with dispatch.",
    whenYouNeed: "Phase 04 Advance through Phase 06 Show.",
    whatYouReceive: "Transportation plan, dispatch operations, daily reports.",
    whereItOperates: "APS L2.",
  },
  {
    number: 40,
    slug: "visa-immigration-cross-border-logistics",
    name: "Visa, Immigration & Cross-Border Logistics",
    primaryClass: "0000",
    apsLevels: ["L1"],
    primaryPhase: "01",
    secondaryPhases: ["04"],
    tiers: ["04", "05", "06"],
    whatItIs: "Work visa filings, ATA carnet management, customs brokerage, and cross-border equipment movement.",
    whenYouNeed: "Phase 01 Discovery through Phase 04 Advance.",
    whatYouReceive: "Visa filings, carnet documentation, customs plan.",
    whereItOperates: "APS L1.",
  },
  {
    number: 41,
    slug: "per-diem-travel-reconciliation-operations",
    name: "Per Diem, Travel & Reconciliation Operations",
    primaryClass: "0000",
    crossClass: ["6000"],
    apsLevels: ["L1"],
    primaryPhase: "04",
    secondaryPhases: ["08"],
    tiers: ["04", "05"],
    whatItIs: "Per diem distribution, expense capture, receipt management, and post-event financial reconciliation.",
    whenYouNeed: "Phase 04 Advance through Phase 08 Wrap.",
    whatYouReceive: "Per diem schedule, expense reporting, reconciliation package.",
    whereItOperates: "APS L1.",
  },
  {
    number: 42,
    slug: "production-management-producer-staffing",
    name: "Production Management & Producer Staffing",
    primaryClass: "6000",
    apsLevels: ["L1", "L2"],
    primaryPhase: "01",
    secondaryPhases: "all",
    tiers: ["04", "05", "06"],
    whatItIs:
      "Senior producer, production manager, production coordinator, and production assistant staffing across project lifespan.",
    whenYouNeed: "Phase 01 Discovery through Phase 08 Wrap.",
    whatYouReceive: "Staffed roles, daily reports, scope-of-work tracking.",
    whereItOperates: "APS L1, L2.",
  },
  {
    number: 43,
    slug: "stagehand-rigging-labor",
    name: "Stagehand & Rigging Labor",
    primaryClass: "6000",
    apsLevels: ["L4", "L5"],
    primaryPhase: "05",
    secondaryPhases: ["06", "07"],
    tiers: ["04", "05", "06"],
    whatItIs: "Skilled and general labor for load-in, rigging, build, strike, and load-out operations.",
    whenYouNeed: "Phase 05 Build through Phase 07 Strike.",
    whatYouReceive: "Staffed crews, daily call sheets, time tracking.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 44,
    slug: "specialty-technician-staffing",
    name: "Specialty Technician Staffing (A1, L1, V1, IT)",
    primaryClass: "5000",
    apsLevels: ["L4", "L5"],
    primaryPhase: "05",
    secondaryPhases: ["06", "07"],
    tiers: ["04", "05", "06"],
    whatItIs: "A1, A2, L1, L2, V1, V2, IT, network, and broadcast technicians.",
    whenYouNeed: "Phase 05 Build through Phase 07 Strike.",
    whatYouReceive: "Vetted technicians, certification documentation, daily timesheets.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 45,
    slug: "hospitality-guest-services-staffing",
    name: "Hospitality & Guest Services Staffing",
    primaryClass: "7000",
    apsLevels: ["L3", "L4"],
    primaryPhase: "05",
    secondaryPhases: ["06"],
    tiers: ["04", "05"],
    whatItIs: "Hosts, ushers, registrars, runners, and concierge staff trained to brand standards.",
    whenYouNeed: "Phase 05 Build through Phase 06 Show.",
    whatYouReceive: "Trained staff, briefing decks, daily reporting.",
    whereItOperates: "APS L3, L4.",
  },
  {
    number: 46,
    slug: "security-medical-public-safety-staffing",
    name: "Security, Medical & Public Safety Staffing",
    primaryClass: "6000",
    apsLevels: ["L2", "L3"],
    primaryPhase: "05",
    secondaryPhases: ["06"],
    tiers: ["04", "05"],
    whatItIs: "Licensed security, EMT / paramedic, fire watch, and public safety command staffing.",
    whenYouNeed: "Phase 05 Build through Phase 06 Show.",
    whatYouReceive: "Licensed personnel, post sheets, incident reporting.",
    whereItOperates: "APS L2, L3.",
  },
  {
    number: 47,
    slug: "brand-ambassador-promo-staff",
    name: "Brand Ambassador & Promo Staff",
    primaryClass: "3000",
    apsLevels: ["L4"],
    primaryPhase: "05",
    secondaryPhases: ["06"],
    tiers: ["01", "04", "05"],
    whatItIs: "On-brand ambassadors trained in product knowledge, brand voice, and consumer engagement metrics.",
    whenYouNeed: "Phase 05 Build through Phase 06 Show.",
    whatYouReceive: "Trained ambassadors, scripts, consumer data capture.",
    whereItOperates: "APS L4.",
  },
  {
    number: 48,
    slug: "union-labor-coordination-steward-liaison",
    name: "Union Labor Coordination & Steward Liaison",
    primaryClass: "6000",
    apsLevels: ["L2", "L3"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "Union call management, jurisdictional planning, and steward relations for IATSE, Teamsters, and trade unions.",
    whenYouNeed: "Phase 03 Develop through Phase 06 Show.",
    whatYouReceive: "Union call plan, jurisdiction matrix, steward POC.",
    whereItOperates: "APS L2, L3.",
  },
  {
    number: 49,
    slug: "scenic-design-3d-visualization",
    name: "Scenic Design & 3D Visualization",
    primaryClass: "1000",
    crossClass: ["4000"],
    apsLevels: ["L4", "L5"],
    primaryPhase: "02",
    secondaryPhases: ["03"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "Concept-through-final scenic design with rendered visualization, material studies, and brand integration.",
    whenYouNeed: "Phase 02 Concept through Phase 03 Develop.",
    whatYouReceive: "Concept renderings, material boards, final design package.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 50,
    slug: "engineering-shop-drawings-bom",
    name: "Engineering, Shop Drawings & BOM",
    primaryClass: "4000",
    apsLevels: ["L5", "L6"],
    primaryPhase: "03",
    secondaryPhases: ["05"],
    tiers: ["04", "05", "06"],
    whatItIs: "Buildable engineering with CAD, structural calculations, bill of materials, and shop drawings.",
    whenYouNeed: "Phase 03 Develop.",
    whatYouReceive: "Stamped or unstamped engineering, shop drawings, complete BOM.",
    whereItOperates: "APS L5, L6.",
  },
  {
    number: 51,
    slug: "custom-fabrication-cnc-millwork",
    name: "Custom Fabrication, CNC & Millwork",
    primaryClass: "4000",
    apsLevels: ["L5", "L6"],
    primaryPhase: "05",
    secondaryPhases: ["04", "06"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "Custom-built scenic, props, and environments produced in fabrication facilities — wood, plastic, composites.",
    whenYouNeed: "Phase 05 Build.",
    whatYouReceive: "Built and finished assets, QC documentation, crating.",
    whereItOperates:
      "APS L5, L6. Production across the GHXSTSHIP fabrication network in Miami, New York City, Chicago, and Los Angeles.",
  },
  {
    number: 52,
    slug: "metalwork-welding-structural-build",
    name: "Metalwork, Welding & Structural Build",
    primaryClass: "4000",
    apsLevels: ["L5", "L6"],
    primaryPhase: "05",
    secondaryPhases: ["06"],
    tiers: ["04", "05", "06"],
    whatItIs: "Custom steel, aluminum, and structural metal fabrication — frames, archways, custom rigging.",
    whenYouNeed: "Phase 05 Build.",
    whatYouReceive: "Welded, finished, certified structural elements.",
    whereItOperates: "APS L5, L6.",
  },
  {
    number: 53,
    slug: "large-format-print-vinyl-signage-production",
    name: "Large-Format Print, Vinyl & Signage Production",
    primaryClass: "4000",
    apsLevels: ["L5", "L6"],
    primaryPhase: "05",
    secondaryPhases: ["06"],
    tiers: ["04", "05"],
    whatItIs: "Large-format graphics, dye-sub fabric, vinyl, rigid substrates, and 3D dimensional signage.",
    whenYouNeed: "Phase 05 Build.",
    whatYouReceive: "Printed and finished graphics, hardware, install instructions.",
    whereItOperates: "APS L5, L6.",
  },
  {
    number: 54,
    slug: "modular-touring-scenic-systems",
    name: "Modular & Touring Scenic Systems",
    primaryClass: "4000",
    apsLevels: ["L4", "L5"],
    primaryPhase: "02",
    secondaryPhases: ["05", "07"],
    tiers: ["04", "05", "06"],
    whatItIs: "Reusable scenic systems engineered for repeated deployment with road cases and touring documentation.",
    whenYouNeed: "Phase 02 Concept through Phase 05 Build.",
    whatYouReceive: "Modular system, road cases, touring binder.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 55,
    slug: "asset-storage-refurbishment-redeployment",
    name: "Asset Storage, Refurbishment & Redeployment",
    primaryClass: "4000",
    apsLevels: ["L5", "L6"],
    primaryPhase: "07",
    secondaryPhases: ["01", "08"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "Climate-controlled storage, condition tracking, refurbishment cycles, and redeployment for repeat activations.",
    whenYouNeed: "Phase 07 Strike onward.",
    whatYouReceive: "Storage agreement, condition reports, redeployment scope.",
    whereItOperates: "APS L5, L6.",
  },
  {
    number: 56,
    slug: "fr-treatment-material-certification-pyro-compliance",
    name: "FR Treatment, Material Certification & Pyro Compliance",
    primaryClass: "4000",
    crossClass: ["0000"],
    apsLevels: ["L5", "L6"],
    primaryPhase: "05",
    secondaryPhases: ["06"],
    tiers: ["04", "05", "06"],
    whatItIs: "Flame-retardant treatment, NFPA 701 certification, and pyro proximity compliance for scenic and fabric.",
    whenYouNeed: "Phase 05 Build, with carryover documentation through Phase 06 Show.",
    whatYouReceive: "Treatment certifications, fire marshal-ready documentation.",
    whereItOperates: "APS L5, L6.",
  },
  {
    number: 57,
    slug: "special-event-permit-acquisition",
    name: "Special Event Permit Acquisition",
    primaryClass: "0000",
    apsLevels: ["L1", "L2"],
    primaryPhase: "01",
    secondaryPhases: ["03"],
    tiers: ["04", "05"],
    whatItIs: "Municipal special-event permits, road closures, noise variances, and amplified sound permits.",
    whenYouNeed: "Phase 01 Discovery through Phase 03 Develop.",
    whatYouReceive: "Issued permits, conditions checklist, inspection schedule.",
    whereItOperates: "APS L1, L2.",
  },
  {
    number: 58,
    slug: "event-insurance-procurement",
    name: "Event Insurance Procurement",
    primaryClass: "0000",
    apsLevels: ["L1"],
    primaryPhase: "01",
    secondaryPhases: ["03"],
    tiers: ["04", "05", "06"],
    whatItIs: "General liability, liquor liability, weather, terrorism, cyber, and additional-insured documentation.",
    whenYouNeed: "Phase 01 Discovery through Phase 03 Develop.",
    whatYouReceive: "Bound policies, COIs to all named parties.",
    whereItOperates: "APS L1.",
  },
  {
    number: 59,
    slug: "ada-accessibility-compliance-audit",
    name: "ADA & Accessibility Compliance Audit",
    primaryClass: "0000",
    apsLevels: ["L2", "L3"],
    primaryPhase: "03",
    secondaryPhases: ["05"],
    tiers: ["04", "05"],
    whatItIs: "Pre-event accessibility review, ADA-compliant design recommendations, and on-site validation.",
    whenYouNeed: "Phase 03 Develop through Phase 05 Build.",
    whatYouReceive: "Accessibility audit, mitigation plan, sign-off.",
    whereItOperates: "APS L2, L3.",
  },
  {
    number: 60,
    slug: "fire-life-safety-pyrotechnic-certification",
    name: "Fire, Life Safety & Pyrotechnic Certification",
    primaryClass: "0000",
    crossClass: ["4000"],
    apsLevels: ["L2", "L3"],
    primaryPhase: "03",
    secondaryPhases: ["05"],
    tiers: ["04", "05", "06"],
    whatItIs: "Fire marshal liaison, life-safety planning, pyro permits, and inspection coordination.",
    whenYouNeed: "Phase 03 Develop through Phase 05 Build.",
    whatYouReceive: "Life safety plan, fire marshal sign-off, pyro permits.",
    whereItOperates: "APS L2, L3.",
  },
  {
    number: 61,
    slug: "vendor-subcontractor-compliance-onboarding",
    name: "Vendor & Subcontractor Compliance Onboarding",
    primaryClass: "0000",
    apsLevels: ["L1"],
    primaryPhase: "03",
    secondaryPhases: "all",
    tiers: ["04", "05"],
    whatItIs: "Vendor MSA, COI collection, W9 capture, additional-insured tracking, and compliance matrix management.",
    whenYouNeed: "Phase 03 Develop through Phase 08 Wrap.",
    whatYouReceive: "Compliance matrix, signed MSAs, COI repository.",
    whereItOperates: "APS L1.",
  },
  {
    number: 62,
    slug: "master-service-agreements-sow-architecture",
    name: "Master Service Agreements & SOW Architecture",
    primaryClass: "0000",
    apsLevels: ["L1"],
    primaryPhase: "01",
    secondaryPhases: "all",
    tiers: ["04", "05"],
    whatItIs: "Drafted, negotiated MSA and SOW packages with phase-gated payment terms and escalation paths.",
    whenYouNeed: "Phase 01 Discovery through Phase 08 Wrap.",
    whatYouReceive: "Executed MSA, phase-gated SOWs, change-order framework.",
    whereItOperates: "APS L1.",
  },
  {
    number: 63,
    slug: "risk-management-weather-contingency-planning",
    name: "Risk Management & Weather Contingency Planning",
    primaryClass: "0000",
    apsLevels: ["L2"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs: "Weather monitoring, postponement criteria, contingency operations, and decision-tree gating.",
    whenYouNeed: "Phase 03 Develop through Phase 06 Show.",
    whatYouReceive: "Risk register, contingency plan, decision protocol.",
    whereItOperates: "APS L2.",
  },
  {
    number: 64,
    slug: "post-event-reconciliation-financial-close",
    name: "Post-Event Reconciliation & Financial Close",
    primaryClass: "0000",
    apsLevels: ["L1"],
    primaryPhase: "08",
    secondaryPhases: [],
    tiers: ["04", "05"],
    whatItIs: "Vendor invoice reconciliation, change-order closeout, final cost report, and project P&L.",
    whenYouNeed: "Phase 08 Wrap.",
    whatYouReceive: "Reconciliation package, final P&L, archive document set.",
    whereItOperates: "APS L1.",
  },
  {
    number: 65,
    slug: "sustainability-reporting-esg-documentation",
    name: "Sustainability Reporting & ESG Documentation",
    primaryClass: "0000",
    apsLevels: ["L1"],
    primaryPhase: "08",
    secondaryPhases: [],
    tiers: ["04", "05"],
    whatItIs:
      "Post-event measurement of waste diversion, energy / water usage, carbon footprint, and ESG-aligned reporting.",
    whenYouNeed: "Phase 08 Wrap.",
    whatYouReceive: "Sustainability report, measurement data, brand-ready summary.",
    whereItOperates: "APS L1.",
  },
  {
    number: 66,
    slug: "asset-cataloging-portfolio-documentation",
    name: "Asset Cataloging & Portfolio Documentation",
    primaryClass: "0000",
    crossClass: ["1000"],
    apsLevels: ["L1", "L5"],
    primaryPhase: "08",
    secondaryPhases: [],
    tiers: ["01", "02", "04", "05"],
    whatItIs: "Photo / video documentation, asset cataloging, portfolio submission, and case-study production.",
    whenYouNeed: "Phase 08 Wrap onward.",
    whatYouReceive: "Asset catalog, photo / video library, case study package.",
    whereItOperates: "APS L1, L5.",
  },
  {
    number: 67,
    slug: "touring-site-adaptation-multi-city-routing",
    name: "Touring Site Adaptation & Multi-City Routing",
    primaryClass: "4000",
    crossClass: ["6000"],
    apsLevels: ["L1", "L2", "L3"],
    primaryPhase: "01",
    secondaryPhases: ["03", "04"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "Adapting one production to multiple venues across a tour leg with venue-specific load-in, sightline, capacity, and rigging adjustments.",
    whenYouNeed: "Phase 01 Discovery for routing; Phase 03 Develop for per-venue adaptation.",
    whatYouReceive: "Tour routing plan, venue-by-venue adaptation matrix, advance schedule.",
    whereItOperates: "APS L1, L2, L3.",
  },
  {
    number: 68,
    slug: "remote-exotic-destination-site-logistics",
    name: "Remote & Exotic Destination Site Logistics",
    primaryClass: "4000",
    crossClass: ["6000"],
    apsLevels: ["L1", "L2"],
    primaryPhase: "01",
    secondaryPhases: ["04", "05"],
    tiers: ["04", "05"],
    whatItIs:
      "Mobilization to remote destinations — private islands, jungle, desert, mountain, maritime — with full infrastructure import.",
    whenYouNeed: "Phase 01 Discovery through Phase 04 Advance.",
    whatYouReceive: "Mobilization plan, infrastructure spec, local fixer roster.",
    whereItOperates: "APS L1, L2.",
  },
  {
    number: 69,
    slug: "campus-academic-venue-operations",
    name: "Campus & Academic Venue Operations",
    primaryClass: "4000",
    crossClass: ["0000"],
    apsLevels: ["L2", "L3"],
    primaryPhase: "01",
    secondaryPhases: "all",
    tiers: ["04", "05", "06"],
    whatItIs:
      "Production within academic environments with FERPA awareness, student safety protocols, university procurement, and Title IX / Clery alignment.",
    whenYouNeed: "Phase 01 Discovery through Phase 08 Wrap.",
    whatYouReceive: "Campus operations plan, university procurement compliance, security coordination.",
    whereItOperates: "APS L2, L3.",
  },
  {
    number: 70,
    slug: "festival-multi-stage-site-master-planning",
    name: "Festival & Multi-Stage Site Master Planning",
    primaryClass: "4000",
    apsLevels: ["L2", "L3"],
    primaryPhase: "02",
    secondaryPhases: ["03", "05"],
    tiers: ["04", "05"],
    whatItIs:
      "Site master planning for multi-stage festivals covering circulation, vendor village, art, camping, sponsor zones, and FOH placement.",
    whenYouNeed: "Phase 02 Concept through Phase 03 Develop.",
    whatYouReceive: "Festival site plan, capacity zoning, infrastructure hierarchy.",
    whereItOperates: "APS L2, L3.",
  },
  {
    number: 71,
    slug: "main-stage-design-production-engineering",
    name: "Main Stage Design & Production Engineering",
    primaryClass: "5000",
    crossClass: ["4000"],
    apsLevels: ["L4", "L5"],
    primaryPhase: "02",
    secondaryPhases: ["03", "05", "06"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "End-to-end main stage architecture — structural design, scenic integration, video, lighting, audio in unified package for concerts, festivals, and large-scale activations.",
    whenYouNeed: "Phase 02 Concept through Phase 05 Build.",
    whatYouReceive: "Stage design package, structural engineering, rigging plan, integrated production design.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 72,
    slug: "projection-mapping-ar-vr-integration",
    name: "Projection Mapping, AR & VR Integration",
    primaryClass: "9000",
    crossClass: ["5000"],
    apsLevels: ["L4", "L5"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["02", "03", "04", "05", "06"],
    whatItIs:
      "Spatial computing and projected media — large-scale projection mapping, AR overlays, VR integration, and headset-driven environments.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Mapping content, projection design, AR / VR integration, on-site programming.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 73,
    slug: "theatrical-lighting-plot-sound-design",
    name: "Theatrical Lighting Plot & Sound Design",
    primaryClass: "5000",
    apsLevels: ["L4", "L5"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["06"],
    whatItIs:
      "Narrative-driven lighting and sound design for theatrical and immersive performance — character cueing, emotional pacing, and scene-level operation.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Light plot, sound design score, programming, theatrical operator staffing.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 74,
    slug: "broadcast-ob-truck-technical-operations",
    name: "Broadcast & OB Truck Technical Operations",
    primaryClass: "5000",
    crossClass: ["9000"],
    apsLevels: ["L4", "L5"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["02", "06"],
    whatItIs:
      "Outside broadcast operations — OB truck integration, multi-feed switching, broadcast graphics, master control, and transmission to network or stream.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Broadcast architecture, OB integration, graphics package, master control staffing.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 75,
    slug: "interactive-technology-sensor-integration",
    name: "Interactive Technology & Sensor Integration",
    primaryClass: "9000",
    apsLevels: ["L4", "L5"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["02", "03", "04", "05"],
    whatItIs:
      "IoT, sensor-driven, gesture-responsive, biometric-triggered, and data-driven experience integration for immersive and brand environments.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Interactive architecture, sensor deployment, content trigger logic, on-site operators.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 76,
    slug: "athlete-sports-talent-hospitality",
    name: "Athlete & Sports Talent Hospitality",
    primaryClass: "8000",
    apsLevels: ["L3", "L4"],
    primaryPhase: "05",
    secondaryPhases: ["06"],
    tiers: ["04", "05"],
    whatItIs:
      "Hospitality operations specific to professional and amateur athletes — locker room, training room, recovery room, family hospitality, and sponsor obligation management.",
    whenYouNeed: "Phase 05 Build through Phase 06 Show.",
    whatYouReceive: "Athlete hospitality plan, family liaison, training / medical coordination.",
    whereItOperates: "APS L3, L4.",
  },
  {
    number: 77,
    slug: "donor-alumni-patron-cultivation-programs",
    name: "Donor, Alumni & Patron Cultivation Programs",
    primaryClass: "3000",
    crossClass: ["7000"],
    apsLevels: ["L4"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["01", "04", "05"],
    whatItIs:
      "High-touch hospitality for major donors, alumni, board members, and arts patrons in academic and cultural settings.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Cultivation program design, host scripting, follow-up CRM integration.",
    whereItOperates: "APS L4.",
  },
  {
    number: 78,
    slug: "press-media-junket-hospitality",
    name: "Press, Media & Junket Hospitality",
    primaryClass: "8000",
    crossClass: ["3000"],
    apsLevels: ["L3", "L4"],
    primaryPhase: "05",
    secondaryPhases: ["06"],
    tiers: ["01", "04", "05"],
    whatItIs:
      "Press junket production, media check-in, talent rotation, embargo management, and press-corps hospitality for film, brand, and entertainment launches.",
    whenYouNeed: "Phase 05 Build through Phase 06 Show.",
    whatYouReceive: "Junket schedule, press credential ops, talent rotation plan, daily reports.",
    whereItOperates: "APS L3, L4.",
  },
  {
    number: 79,
    slug: "wedding-private-estate-hospitality-production",
    name: "Wedding & Private Estate Hospitality Production",
    primaryClass: "8000",
    apsLevels: ["L1", "L2", "L3"],
    primaryPhase: "01",
    secondaryPhases: "all",
    tiers: ["04", "05"],
    whatItIs:
      "Full wedding and private estate event production with discretion, custom programming, bespoke service, and household staff coordination.",
    whenYouNeed: "Phase 01 Discovery through Phase 08 Wrap.",
    whatYouReceive: "Event design, vendor curation, NDA framework, day-of execution.",
    whereItOperates: "APS L1, L2, L3.",
  },
  {
    number: 80,
    slug: "chef-led-pop-up-culinary-direction",
    name: "Chef-Led Pop-Up & Culinary Direction",
    primaryClass: "8000",
    apsLevels: ["L4"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "Curated chef collaborations, omakase, and chef-led pop-up dining production with culinary direction, BOH ops, and front-of-house service training.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Chef partnership agreement, menu development, BOH plan, sommelier and service program.",
    whereItOperates: "APS L4.",
  },
  {
    number: 81,
    slug: "wellness-performance-healthy-fb-catering",
    name: "Wellness, Performance & Healthy F&B Catering",
    primaryClass: "8000",
    apsLevels: ["L4"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "Performance-aligned, allergen-aware, and wellness-philosophy F&B for athlete, wellness, and health-event audiences with macro tracking and dietary flexibility.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Performance menu, dietary matrix, vendor sourcing, on-site execution.",
    whereItOperates: "APS L4.",
  },
  {
    number: 82,
    slug: "festival-fb-vendor-curation-management",
    name: "Festival F&B Vendor Curation & Management",
    primaryClass: "8000",
    apsLevels: ["L3", "L4"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "Multi-vendor festival F&B program design, vendor curation, contract negotiation, vendor village operations, and post-festival settlement.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Vendor roster, contract package, vendor village ops, settlement.",
    whereItOperates: "APS L3, L4.",
  },
  {
    number: 83,
    slug: "pop-up-fb-health-permit-mobile-vendor-compliance",
    name: "Pop-Up F&B Health Permit & Mobile Vendor Compliance",
    primaryClass: "0000",
    crossClass: ["8000"],
    apsLevels: ["L2", "L3"],
    primaryPhase: "03",
    secondaryPhases: ["05"],
    tiers: ["04", "05"],
    whatItIs:
      "Health department permits, mobile food unit certification, sanitation plan, and inspection coordination for pop-up and mobile F&B operations.",
    whenYouNeed: "Phase 03 Develop through Phase 05 Build.",
    whatYouReceive: "Permits, certifications, sanitation plan, inspection sign-off.",
    whereItOperates: "APS L2, L3.",
  },
  {
    number: 84,
    slug: "boutique-brand-launch-buildout",
    name: "Boutique & Brand Launch Buildout",
    primaryClass: "7000",
    apsLevels: ["L3", "L4"],
    primaryPhase: "02",
    secondaryPhases: ["03", "05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "Luxury boutique buildout for permanent or limited-run launches with merchandising, fixturing, brand environment, and opening event.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Boutique design, fixture package, merchandising plan, brand environment.",
    whereItOperates: "APS L3, L4.",
  },
  {
    number: 85,
    slug: "trade-show-booth-design-build",
    name: "Trade Show Booth Design & Build",
    primaryClass: "7000",
    crossClass: ["4000"],
    apsLevels: ["L4", "L5"],
    primaryPhase: "02",
    secondaryPhases: ["03", "05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "Trade show and convention booth design, modular build, electrical / AV integration, and on-site assembly per show in the calendar.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Booth design, build package, AV / electrical integration, on-site crew.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 86,
    slug: "touring-merchandise-operations",
    name: "Touring Merchandise Operations",
    primaryClass: "7000",
    apsLevels: ["L4", "L5"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06", "07"],
    tiers: ["04", "05"],
    whatItIs: "Tour merch operations — design, sourcing, on-site retail, daily settlement, and tour-leg replenishment.",
    whenYouNeed: "Phase 02 Concept through Phase 07 Strike.",
    whatYouReceive: "Merch line, sourcing, on-site retail ops, daily settlement.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 87,
    slug: "touring-mobile-production-office",
    name: "Touring & Mobile Production Office",
    primaryClass: "6000",
    apsLevels: ["L2", "L3"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06", "07"],
    tiers: ["04", "05"],
    whatItIs:
      "Mobile production office that travels with a tour or multi-city deployment — connectivity, comms, document management, and deployable infrastructure that lands ready in each market.",
    whenYouNeed: "Phase 03 Develop through Phase 07 Strike.",
    whatYouReceive: "Mobile office unit, satellite / cellular connectivity, comms, deployable infrastructure.",
    whereItOperates: "APS L2, L3.",
  },
  {
    number: 88,
    slug: "tour-bus-crew-coach-coordination",
    name: "Tour Bus & Crew Coach Coordination",
    primaryClass: "6000",
    apsLevels: ["L1", "L2"],
    primaryPhase: "04",
    secondaryPhases: ["05", "06", "07"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "Tour bus sourcing, driver staffing, route planning, and bus-life logistics for touring crew and artist parties.",
    whenYouNeed: "Phase 04 Advance through Phase 07 Strike.",
    whatYouReceive: "Bus contracts, driver staffing, route plan, bus-life ops.",
    whereItOperates: "APS L1, L2.",
  },
  {
    number: 89,
    slug: "athlete-team-travel-operations",
    name: "Athlete & Team Travel Operations",
    primaryClass: "6000",
    crossClass: ["2000"],
    apsLevels: ["L1", "L2"],
    primaryPhase: "04",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "Charter flights, ground operations, accommodations, and per diem for athletic teams, tournament fields, and collegiate sport travel.",
    whenYouNeed: "Phase 04 Advance through Phase 06 Show.",
    whatYouReceive: "Charter ops, ground plan, accommodation block, team logistics.",
    whereItOperates: "APS L1, L2.",
  },
  {
    number: 90,
    slug: "destination-event-travel-local-fixer-network",
    name: "Destination Event Travel & Local Fixer Network",
    primaryClass: "6000",
    apsLevels: ["L1", "L2"],
    primaryPhase: "04",
    secondaryPhases: ["05", "06", "07"],
    tiers: ["04", "05"],
    whatItIs:
      "Destination event travel coordination with local fixers — drivers, translators, vendor liaisons, cultural advisors, and in-market trouble-shooters.",
    whenYouNeed: "Phase 04 Advance through Phase 07 Strike.",
    whatYouReceive: "Travel plan, fixer roster, local liaison, in-market support.",
    whereItOperates: "APS L1, L2.",
  },
  {
    number: 91,
    slug: "theatrical-crew-stage-management",
    name: "Theatrical Crew & Stage Management",
    primaryClass: "6000",
    crossClass: ["5000"],
    apsLevels: ["L4", "L5"],
    primaryPhase: "05",
    secondaryPhases: ["06", "07"],
    tiers: ["06"],
    whatItIs:
      "Stage management, deck crew, fly crew, ASMs, and theatrical-spec labor with calling-the-show experience and theatre-grade discipline.",
    whenYouNeed: "Phase 05 Build through Phase 07 Strike.",
    whatYouReceive: "SM, deck / fly crew, calling protocol, performance ops.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 92,
    slug: "curatorial-art-handler-staffing",
    name: "Curatorial & Art Handler Staffing",
    primaryClass: "6000",
    crossClass: ["7000"],
    apsLevels: ["L4", "L5"],
    primaryPhase: "05",
    secondaryPhases: ["04", "06", "07"],
    tiers: ["04", "05"],
    whatItIs:
      "Registrars, art handlers, conservators, and curatorial assistants trained in fine art handling protocols and museum-grade documentation.",
    whenYouNeed: "Phase 05 Build through Phase 07 Strike.",
    whatYouReceive: "Trained handlers, condition reporting, install / de-install crew.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 93,
    slug: "wellness-practitioner-instructor-sourcing",
    name: "Wellness Practitioner & Instructor Sourcing",
    primaryClass: "7000",
    crossClass: ["2000"],
    apsLevels: ["L4"],
    primaryPhase: "04",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "Yoga teachers, meditation guides, breathwork facilitators, fitness instructors, sound healers, somatic practitioners, and wellness experts.",
    whenYouNeed: "Phase 04 Advance through Phase 06 Show.",
    whatYouReceive: "Practitioner roster, scheduling, programming integration.",
    whereItOperates: "APS L4.",
  },
  {
    number: 94,
    slug: "broadcast-crew-field-production-personnel",
    name: "Broadcast Crew & Field Production Personnel",
    primaryClass: "5000",
    apsLevels: ["L4", "L5"],
    primaryPhase: "05",
    secondaryPhases: ["06"],
    tiers: ["02", "06"],
    whatItIs:
      "Camera operators, audio engineers, producers, directors, technical directors, EVS operators, and field production crew with broadcast-grade credentials.",
    whenYouNeed: "Phase 05 Build through Phase 06 Show.",
    whatYouReceive: "Crew roster, certifications, daily call sheets.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 95,
    slug: "theatrical-set-construction-rigging",
    name: "Theatrical Set Construction & Rigging",
    primaryClass: "4000",
    apsLevels: ["L5", "L6"],
    primaryPhase: "05",
    secondaryPhases: ["06"],
    tiers: ["06"],
    whatItIs:
      "Theatrical-spec set construction with traveler rigging, fly system integration, scenic painting, and theatre-grade finish work.",
    whenYouNeed: "Phase 05 Build through Phase 06 Show.",
    whatYouReceive: "Built set, rigging integration, install drawings, road cases.",
    whereItOperates: "APS L5, L6.",
  },
  {
    number: 96,
    slug: "immersive-environment-worldbuilding-fabrication",
    name: "Immersive Environment & Worldbuilding Fabrication",
    primaryClass: "4000",
    crossClass: ["1000"],
    apsLevels: ["L5", "L6"],
    primaryPhase: "05",
    secondaryPhases: ["06"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "Themed environment fabrication for immersive experiences — themed scenic, sculpted finishes, integrated tech, narrative props, and walkthrough environments.",
    whenYouNeed: "Phase 05 Build through Phase 06 Show.",
    whatYouReceive: "Built environments, integrated tech, finish work, install package.",
    whereItOperates: "APS L5, L6.",
  },
  {
    number: 97,
    slug: "trade-show-booth-fabrication-tour-spec-build",
    name: "Trade Show Booth Fabrication & Tour-Spec Build",
    primaryClass: "4000",
    apsLevels: ["L5", "L6"],
    primaryPhase: "05",
    secondaryPhases: ["06", "07"],
    tiers: ["04", "05"],
    whatItIs:
      "Trade show booth fabrication engineered for repeated assembly across show calendar with road cases, assembly docs, and replacement-parts kits.",
    whenYouNeed: "Phase 05 Build; redeployment Phase 07 Strike.",
    whatYouReceive: "Built booth, road cases, assembly drawings, replacement-parts kit.",
    whereItOperates: "APS L5, L6.",
  },
  {
    number: 98,
    slug: "art-installation-engineering-mount-design",
    name: "Art Installation Engineering & Mount Design",
    primaryClass: "4000",
    apsLevels: ["L5", "L6"],
    primaryPhase: "03",
    secondaryPhases: ["05"],
    tiers: ["04", "05"],
    whatItIs:
      "Mount design, plinth fabrication, cleat systems, and conservation-grade installation hardware for fine art and cultural objects.",
    whenYouNeed: "Phase 03 Develop through Phase 05 Build.",
    whatYouReceive: "Mount designs, fabricated plinths, install hardware, conservation documentation.",
    whereItOperates: "APS L5, L6.",
  },
  {
    number: 99,
    slug: "international-destination-permitting",
    name: "International & Destination Permitting",
    primaryClass: "0000",
    apsLevels: ["L1", "L2"],
    primaryPhase: "01",
    secondaryPhases: ["03", "05"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "Permitting and regulatory navigation for international and destination productions — work permits, customs, local entertainment licensing, and cultural compliance.",
    whenYouNeed: "Phase 01 Discovery through Phase 05 Build.",
    whatYouReceive: "Permits, customs documentation, regulatory clearances.",
    whereItOperates: "APS L1, L2.",
  },
  {
    number: 100,
    slug: "broadcast-rights-clearances-music-licensing",
    name: "Broadcast Rights, Clearances & Music Licensing",
    primaryClass: "0000",
    crossClass: ["1000"],
    apsLevels: ["L1"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["02", "06"],
    whatItIs:
      "Broadcast rights, music sync licensing, performer clearances, image rights, and content rights management with audit-ready chain of custody.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Rights register, signed clearances, licensing payments, audit documentation.",
    whereItOperates: "APS L1.",
  },
  {
    number: 101,
    slug: "athletic-sanctioning-league-compliance",
    name: "Athletic Sanctioning & League Compliance",
    primaryClass: "0000",
    apsLevels: ["L1", "L2"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "League rule compliance, official sanctioning body coordination, doping protocol, competition integrity, and conference- / league-specific operating rules.",
    whenYouNeed: "Phase 03 Develop through Phase 06 Show.",
    whatYouReceive: "Sanctioning approval, rule compliance package, official coordination.",
    whereItOperates: "APS L1, L2.",
  },
  {
    number: 102,
    slug: "educational-institution-compliance-title-ix-clery",
    name: "Educational Institution Compliance & Title IX / Clery",
    primaryClass: "0000",
    apsLevels: ["L1"],
    primaryPhase: "01",
    secondaryPhases: "all",
    tiers: ["04", "05"],
    whatItIs:
      "Higher-education compliance — Title IX, Clery Act, FERPA, alcohol policy, student safety, and institutional risk management for campus events.",
    whenYouNeed: "Phase 01 Discovery through Phase 08 Wrap.",
    whatYouReceive: "Compliance plan, institutional sign-off, audit documentation.",
    whereItOperates: "APS L1.",
  },
  {
    number: 103,
    slug: "art-loan-insurance-conservation-documentation",
    name: "Art Loan, Insurance & Conservation Documentation",
    primaryClass: "0000",
    apsLevels: ["L1", "L5"],
    primaryPhase: "01",
    secondaryPhases: "all",
    tiers: ["04", "05"],
    whatItIs:
      "Art loan agreements, condition reports, transit insurance (nail-to-nail), conservation documentation, and provenance tracking for fine art and cultural object handling.",
    whenYouNeed: "Phase 01 Discovery through Phase 08 Wrap.",
    whatYouReceive: "Loan agreements, condition reports, insurance binders, conservation logs.",
    whereItOperates: "APS L1, L5.",
  },
  {
    number: 104,
    slug: "ride-attraction-animatronic-integration",
    name: "Ride, Attraction & Animatronic Integration",
    primaryClass: "5000",
    crossClass: ["9000"],
    apsLevels: ["L4", "L5"],
    primaryPhase: "02",
    secondaryPhases: ["03", "05", "06"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "Mechanical ride, animatronic, character, and special-effect integration into themed environments — show control, ride sequencing, character animation, and themed pyrotechnics.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Ride show control, animatronic programming, integration specifications, operator staffing.",
    whereItOperates: "APS L4, L5.",
  },
  {
    number: 105,
    slug: "nightlife-programming-resident-talent-booking",
    name: "Nightlife Programming & Resident Talent Booking",
    primaryClass: "2000",
    apsLevels: ["L1", "L4"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "Resident DJ booking, talent rotations, opening lineups, table-side programming, and night-by-night programming for nightclubs and entertainment venues.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Talent calendar, booking contracts, performance riders, nightly run sheets.",
    whereItOperates: "APS L1, L4.",
  },
  {
    number: 106,
    slug: "bottle-service-vip-table-program-design",
    name: "Bottle Service & VIP Table Program Design",
    primaryClass: "8000",
    apsLevels: ["L4"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "Bottle service program — table inventory, premium spirits curation, presentation theatrics (sparklers, parades, custom presentations), and revenue-per-table optimization for nightclubs and premium venues.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Bottle service menu, table layout, server training, revenue model.",
    whereItOperates: "APS L4.",
  },
  {
    number: 107,
    slug: "yacht-marine-private-aviation-hospitality",
    name: "Yacht, Marine & Private Aviation Hospitality",
    primaryClass: "8000",
    apsLevels: ["L3", "L4"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "Hospitality production aboard yachts, charter aircraft, and private vessels — onboard service, provisioning, crew coordination, and port-of-call programming.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive: "Onboard hospitality plan, provisioning, crew direction, day-of execution.",
    whereItOperates: "APS L3, L4.",
  },
  {
    number: 108,
    slug: "maritime-production-onboard-entertainment-operations",
    name: "Maritime Production & Onboard Entertainment Operations",
    primaryClass: "4000",
    crossClass: ["5000"],
    apsLevels: ["L1", "L2", "L3"],
    primaryPhase: "01",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05", "06"],
    whatItIs:
      "Production aboard cruise ships and large vessels — onboard show production, deck activation, port-day programming, and ship-spec technical adaptation against vessel power, weight, and stability constraints.",
    whenYouNeed: "Phase 01 Discovery through Phase 06 Show.",
    whatYouReceive: "Onboard production plan, ship technical adaptation, port-day programming, crew / staffing.",
    whereItOperates: "APS L1, L2, L3.",
  },
  {
    number: 109,
    slug: "institutional-membership-donor-patron-tier-programs",
    name: "Institutional Membership, Donor & Patron Tier Programs",
    primaryClass: "3000",
    crossClass: ["7000"],
    apsLevels: ["L1", "L4"],
    primaryPhase: "01",
    secondaryPhases: "all",
    tiers: ["01", "04", "05"],
    whatItIs:
      "Tiered membership programs for cultural and academic institutions — patron levels, donor benefits, gala programming, lifetime member services, and stewardship CRM.",
    whenYouNeed: "Phase 01 Discovery through Phase 08 Wrap.",
    whatYouReceive: "Tier architecture, member journey, gala program, CRM integration.",
    whereItOperates: "APS L1, L4.",
  },
  {
    number: 110,
    slug: "amusement-device-ride-safety-compliance",
    name: "Amusement Device & Ride Safety Compliance",
    primaryClass: "0000",
    apsLevels: ["L1", "L5"],
    primaryPhase: "03",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "ASTM F24 amusement ride compliance, third-party inspection, operator training certification, and incident reporting per state amusement device authority.",
    whenYouNeed: "Phase 03 Develop through Phase 06 Show.",
    whatYouReceive: "Inspection certifications, operator training, incident protocols, regulatory liaison.",
    whereItOperates: "APS L1, L5.",
  },
  {
    number: 111,
    slug: "maritime-safety-uscg-imo-compliance",
    name: "Maritime Safety, USCG & IMO Compliance",
    primaryClass: "0000",
    apsLevels: ["L1", "L2"],
    primaryPhase: "01",
    secondaryPhases: ["05", "06"],
    tiers: ["04", "05"],
    whatItIs:
      "U.S. Coast Guard and International Maritime Organization compliance for productions aboard vessels — passenger safety drills, crew certification, environmental compliance, and SOLAS adherence.",
    whenYouNeed: "Phase 01 Discovery through Phase 06 Show.",
    whatYouReceive: "USCG / IMO compliance package, crew certifications, safety plans, regulatory clearances.",
    whereItOperates: "APS L1, L2.",
  },
  {
    number: 112,
    slug: "mega-event-host-city-federation-liaison",
    name: "Mega-Event Host City & Federation Liaison",
    primaryClass: "0000",
    crossClass: ["3000"],
    apsLevels: ["L1", "L2"],
    primaryPhase: "01",
    secondaryPhases: "all",
    tiers: ["04", "05", "06"],
    whatItIs:
      "Relationship management with host city committees, organizing federations (FIFA, IOC, FIA, USOPC, NFL, NBA, MLB, NCAA), sanctioning bodies, and host-city special event authorities for mega-event productions — including accreditation, brand-rights compliance, and clean-zone enforcement.",
    whenYouNeed: "Phase 01 Discovery through Phase 08 Wrap.",
    whatYouReceive:
      "Host city accreditation, federation compliance, branding-guideline adherence, official partnership documentation.",
    whereItOperates: "APS L1, L2.",
  },
  {
    number: 113,
    slug: "fan-zone-programming-sponsor-activation-village",
    name: "Fan Zone Programming & Sponsor Activation Village",
    primaryClass: "7000",
    crossClass: ["3000"],
    apsLevels: ["L2", "L3", "L4"],
    primaryPhase: "02",
    secondaryPhases: ["05", "06"],
    tiers: ["01", "04", "05"],
    whatItIs:
      "Programming and operating fan zones, sponsor villages, and hospitality houses adjacent to or surrounding mega sporting events — Olympic Hospitality Houses (USA House, Heineken House), Olympic Live Sites, Super Bowl Experience, World Cup Fan Fests, NCAA Final Four Fan Fests, and host-city activation footprints.",
    whenYouNeed: "Phase 02 Concept through Phase 06 Show.",
    whatYouReceive:
      "Fan zone master plan, sponsor activation calendar, programming run-of-show, integrated brand and federation compliance.",
    whereItOperates: "APS L2, L3, L4.",
  },
  {
    number: 114,
    slug: "premium-sporting-hospitality-suite-paddock-club-operations",
    name: "Premium Sporting Hospitality Suite & Paddock Club Operations",
    primaryClass: "8000",
    crossClass: ["7000"],
    apsLevels: ["L3", "L4"],
    primaryPhase: "05",
    secondaryPhases: ["06"],
    tiers: ["04", "05"],
    whatItIs:
      "Operations for premium sporting hospitality formats — F1 Paddock Club, Super Bowl Club Seat hospitality, Masters Hospitality Village, Olympic Hospitality Houses, World Cup VIP Hospitality, US Open Suites, and tournament-pavilion programs.",
    whenYouNeed: "Phase 05 Build through Phase 06 Show.",
    whatYouReceive:
      "Suite / club operations binder, multi-day F&B program, talent appearance schedule, athlete meet-and-greet ops, host staffing.",
    whereItOperates: "APS L3, L4.",
  },
];

export const SERVICE_BY_NUMBER = Object.fromEntries(SERVICES.map((s) => [s.number, s])) as Record<number, Service>;
export const SERVICE_BY_SLUG = Object.fromEntries(SERVICES.map((s) => [s.slug, s])) as Record<string, Service>;

/** All services whose primaryClass matches the given XTC code. */
export function servicesByClass(code: Service["primaryClass"]): Service[] {
  return SERVICES.filter((s) => s.primaryClass === code);
}

/** All services that include the given class as primary or cross. */
export function servicesByClassOrCross(code: Service["primaryClass"]): Service[] {
  return SERVICES.filter((s) => s.primaryClass === code || s.crossClass?.includes(code));
}

/** Services anchored to a phase (primary or secondary). */
export function servicesByPhase(phase: Service["primaryPhase"]): Service[] {
  return SERVICES.filter(
    (s) =>
      s.primaryPhase === phase ||
      s.secondaryPhases === "all" ||
      (Array.isArray(s.secondaryPhases) && s.secondaryPhases.includes(phase)),
  );
}
